import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/assets/styles/globals.scss";
import "@ant-design/v5-patch-for-react-19";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" href="../assets/images/heart.png" type={'image/png'}/>
        <link rel="preload" href="../assets/video/dudu.gif" type={'image/gif'}/>
        <link rel="preload" href="../assets/video/dudu2.gif" type={'image/gif'}/>
        <link rel="preload" href="../assets/video/dudu3.gif" type={'image/gif'}/>
        <link rel="preload" href="../assets/video/dudu4.gif" type={'image/gif'}/>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>{children}</body>
    </html>
  );
}
